import React from 'react'
import { NavLink } from 'react-router-dom'

/* Mas o menos este seria el documento de ejemplo si tuviera terminos y condiciones
La cual es sencillo, para no escribir informacion innecesaria se utilizo el texto de ejemplo Lorem Ipsum */

export const TermsNConditions = () => {
  return (
    <div className='container m-5 text-center'>
      <h3 className='display-3'>Terminos y condiciones</h3>
      <hr />
      <br />
      <p className='display-5'>I. Privacidad</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <br />
      <p className='display-5'>II. Condiciones de uso</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <br />
      <p className='display-5'>III. Recopilacion de datos</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <br />
      <p className='display-5'>IV. Uso de Cookies</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <p className='mb-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in cursus turpis massa tincidunt dui ut. At urna condimentum mattis pellentesque id. Eu sem integer vitae justo eget magna fermentum iaculis eu. Est placerat in egestas erat imperdiet. Magna fermentum iaculis eu non diam phasellus vestibulum. Accumsan tortor posuere ac ut consequat semper viverra nam. Est velit egestas dui id ornare arcu odio ut. Non quam lacus suspendisse faucibus interdum. Porttitor rhoncus dolor purus non enim praesent elementum. Gravida neque convallis a cras semper auctor neque. Orci nulla pellentesque dignissim enim.</p>
      <br />
      <NavLink to='/register'>Regresar</NavLink>
    </div>
  )
}
